In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('./생활인구1인가구도로율.csv')
df

     구_x   행정동  1인가구       행정동코드     생활인구   동면적     도로율      도로면적
0    종로구   사직동  1487  11110530.0  24657.0  1.23  0.2144  0.263712
1    종로구   삼청동   380  11110540.0   5117.0  1.49  0.2144  0.319456
2    종로구   부암동  1129  11110550.0  14329.0  2.27  0.2144  0.486688
3    종로구   평창동  1302  11110560.0  17452.0  8.87  0.2144  1.901728
4    종로구   무악동   494  11110570.0   6890.0  0.36  0.2144  0.077184
..   ...   ...   ...         ...      ...   ...     ...       ...
421  강동구  둔촌1동     6  11740690.0   4470.0  0.92  0.2432  0.223744
422  강동구  둔촌2동  2389  11740700.0  27077.0  0.98  0.2432  0.238336
423  강동구  암사1동  4551  11740570.0  27282.0  1.02  0.2432  0.248064
424  강동구  천호2동  6378  11740610.0  44371.0  1.57  0.2432  0.381824
425  강동구    길동  6909  11740685.0  56112.0  2.17  0.2432  0.527744

[426 rows x 8 columns]

In [4]:
accident = pd.read_csv('./데이터/생활인구_동이름코드_중경상.csv')
accident

      행정구   행정동     행정동코드   생활인구  사망자수  중상자수  경상자수
0     송파구  가락1동  11710631  26012     0    67     4
1     강서구  가양1동  11500603  50311     0    69    16
2     은평구  갈현1동  11380551  23815     0    23     5
3     강남구  개포1동  11680660   8830     0    39    12
4     강서구   공항동  11500620  34201     0     9     4
..    ...   ...       ...    ...   ...   ...   ...
419   강서구  화곡6동  11500591  20373     0     0     0
420   강서구  화곡8동  11500593  26527     0     0     0
421   강서구  화곡본동  11500590  28260     0     0     0
422    중구   회현동  11140540  25595     0     0     0
423  동대문구  휘경2동  11230730  19956     0     0     0

[424 rows x 7 columns]

In [5]:
accident = accident.drop(columns=['행정동코드', '생활인구'])
accident

      행정구   행정동  사망자수  중상자수  경상자수
0     송파구  가락1동     0    67     4
1     강서구  가양1동     0    69    16
2     은평구  갈현1동     0    23     5
3     강남구  개포1동     0    39    12
4     강서구   공항동     0     9     4
..    ...   ...   ...   ...   ...
419   강서구  화곡6동     0     0     0
420   강서구  화곡8동     0     0     0
421   강서구  화곡본동     0     0     0
422    중구   회현동     0     0     0
423  동대문구  휘경2동     0     0     0

[424 rows x 5 columns]

In [6]:
final = pd.merge(df, accident, how='left', on='행정동')
final

,구_x,행정동,1인가구,행정동코드,생활인구,동면적,도로율,도로면적,행정구,사망자수,중상자수,경상자수
0,종로구,사직동,1487,11110530.0,24657.0,1.23,0.2144,0.263712,종로구,0.0,3.0,2.0
1,종로구,삼청동,380,11110540.0,5117.0,1.49,0.2144,0.319456,종로구,0.0,2.0,0.0
2,종로구,부암동,1129,11110550.0,14329.0,2.27,0.2144,0.486688,종로구,0.0,1.0,0.0
3,종로구,평창동,1302,11110560.0,17452.0,8.87,0.2144,1.901728,종로구,0.0,21.0,2.0
4,종로구,무악동,494,11110570.0,6890.0,0.36,0.2144,0.077184,종로구,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
425,강동구,둔촌1동,6,11740690.0,4470.0,0.92,0.2432,0.223744,강동구,0.0,16.0,2.0
426,강동구,둔촌2동,2389,11740700.0,27077.0,0.98,0.2432,0.238336,강동구,0.0,2.0,0.0
427,강동구,암사1동,4551,11740570.0,27282.0,1.02,0.2432,0.248064,강동구,0.0,33.0,10.0
428,강동구,천호2동,6378,11740610.0,44371.0,1.57,0.2432,0.381824,강동구,0.0,0.0,0.0
429,강동구,길동,6909,11740685.0,56112.0,2.17,0.2432,0.527744,강동구,0.0,33.0,7.0

In [7]:
final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 430 entries, 0 to 429
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   구_x     430 non-null    object
 1   행정동     430 non-null    object
 2   1인가구    430 non-null    int64
 3   행정동코드   429 non-null    float64
 4   생활인구    429 non-null    float64
 5   동면적     430 non-null    float64
 6   도로율     430 non-null    float64
 7   도로면적    430 non-null    float64
 8   행정구     429 non-null    object
 9   사망자수    429 non-null    float64
 10  중상자수    429 non-null    float64
 11  경상자수    429 non-null    float64
dtypes: float64(8), int64(1), object(3)
memory usage: 43.7+ KB

In [8]:
final = final.drop(columns=['행정구','동면적','도로율'])
final

     구_x   행정동  1인가구       행정동코드     생활인구      도로면적  사망자수  중상자수  경상자수
0    종로구   사직동  1487  11110530.0  24657.0  0.263712   0.0   3.0   2.0
1    종로구   삼청동   380  11110540.0   5117.0  0.319456   0.0   2.0   0.0
2    종로구   부암동  1129  11110550.0  14329.0  0.486688   0.0   1.0   0.0
3    종로구   평창동  1302  11110560.0  17452.0  1.901728   0.0  21.0   2.0
4    종로구   무악동   494  11110570.0   6890.0  0.077184   0.0   1.0   0.0
..   ...   ...   ...         ...      ...       ...   ...   ...   ...
425  강동구  둔촌1동     6  11740690.0   4470.0  0.223744   0.0  16.0   2.0
426  강동구  둔촌2동  2389  11740700.0  27077.0  0.238336   0.0   2.0   0.0
427  강동구  암사1동  4551  11740570.0  27282.0  0.248064   0.0  33.0  10.0
428  강동구  천호2동  6378  11740610.0  44371.0  0.381824   0.0   0.0   0.0
429  강동구    길동  6909  11740685.0  56112.0  0.527744   0.0  33.0   7.0

[430 rows x 9 columns]

In [9]:
final.to_csv('./최종이었으면좋겠다.csv', encoding='utf-8', index=False)