In [1]:
import seaborn as sns
import pandas as pd

In [5]:
df = pd.read_csv('./다행히개인폴더/2차전처리본_도로율수정.csv')
df

,행정동,구_x,행정동코드,1인가구,생활인구,동면적,도로율,도로면적,사망자수,중상자수,경상자수,교차로,단일
0,강남신사,강남구,11680510,1094.0,75610,2.53,0.2406,0.617358,1,51,7,22,23
1,개포동,강남구,11680660,3888.0,49830,5.27,0.2406,1.267962,0,39,12,24,15
2,논현동,강남구,11680521,11739.0,88619,2.72,0.2406,0.654432,0,139,27,49,67
3,대치동,강남구,11680600,6426.0,119943,3.52,0.2406,0.846912,3,94,7,41,52
4,도곡동,강남구,11680655,3280.0,65611,2.04,0.2406,0.490824,1,40,9,22,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,면목동,중랑구,11260565,22193.0,113863,6.01,0.2601,1.563201,3,154,26,71,75
200,묵동,중랑구,11260620,6790.0,44265,1.87,0.2601,0.486387,0,50,8,27,18
201,상봉동,중랑구,11260580,7686.0,43730,1.53,0.2601,0.397953,0,71,12,41,26
202,신내동,중랑구,11260680,2426.0,34433,2.56,0.2601,0.665856,0,42,11,19,18
203,중화동,중랑구,11260600,2353.0,16755,0.64,0.2601,0.166464,0,60,5,20,37

In [6]:
df= df.drop(columns=['행정동코드','구_x'])
df

      행정동     1인가구    생활인구   동면적     도로율      도로면적  사망자수  중상자수  경상자수  교차로  단일
0    강남신사   1094.0   75610  2.53  0.2406  0.617358     1    51     7   22  23
1     개포동   3888.0   49830  5.27  0.2406  1.267962     0    39    12   24  15
2     논현동  11739.0   88619  2.72  0.2406  0.654432     0   139    27   49  67
3     대치동   6426.0  119943  3.52  0.2406  0.846912     3    94     7   41  52
4     도곡동   3280.0   65611  2.04  0.2406  0.490824     1    40     9   22  19
..    ...      ...     ...   ...     ...       ...   ...   ...   ...  ...  ..
199   면목동  22193.0  113863  6.01  0.2601  1.563201     3   154    26   71  75
200    묵동   6790.0   44265  1.87  0.2601  0.486387     0    50     8   27  18
201   상봉동   7686.0   43730  1.53  0.2601  0.397953     0    71    12   41  26
202   신내동   2426.0   34433  2.56  0.2601  0.665856     0    42    11   19  18
203   중화동   2353.0   16755  0.64  0.2601  0.166464     0    60     5   20  37

[204 rows x 11 columns]

In [7]:
df_corr = df.corr(method='pearson')
df_corr

,1인가구,생활인구,동면적,도로율,도로면적,사망자수,중상자수,경상자수,교차로,단일
1인가구,1.000000,0.803521,0.589426,0.114675,0.598471,0.318192,0.698387,0.664699,0.687228,0.655161
생활인구,0.803521,1.000000,0.687655,0.157609,0.695240,0.339846,0.645256,0.595248,0.626126,0.638771
동면적,0.589426,0.687655,1.000000,0.117354,0.990871,0.264420,0.367514,0.397995,0.386498,0.322690
도로율,0.114675,0.157609,0.117354,1.000000,0.197205,-0.037160,0.072605,0.061558,0.056727,0.083114
도로면적,0.598471,0.695240,0.990871,0.197205,1.000000,0.257466,0.372996,0.402496,0.388571,0.331967
사망자수,0.318192,0.339846,0.264420,-0.037160,0.257466,1.000000,0.443647,0.400963,0.472671,0.446726
중상자수,0.698387,0.645256,0.367514,0.072605,0.372996,0.443647,1.000000,0.891246,0.974847,0.958499
경상자수,0.664699,0.595248,0.397995,0.061558,0.402496,0.400963,0.891246,1.000000,0.880514,0.828471
교차로,0.687228,0.626126,0.386498,0.056727,0.388571,0.472671,0.974847,0.880514,1.000000,0.880127
단일,0.655161,0.638771,0.322690,0.083114,0.331967,0.446726,0.958499,0.828471,0.880127,1.000000

In [9]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import KMeans

In [10]:
minmax_scaler = MinMaxScaler()
minmax_scaled = minmax_scaler.fit_transform(df)

minmax_df = pd.DataFrame(minmax_scaled, columns=['1인가구','생활인구','도로면적','사망자수','중상자수','경상자수'])

ValueError: could not convert string to float: '강남신사'

In [25]:
minmax_df

         1인가구      생활인구      도로면적  사망자수      중상자수      경상자수
0    0.110284  0.204108  0.065238   0.0  0.012658  0.041667
1    0.027850  0.020325  0.082170   0.0  0.008439  0.000000
2    0.083625  0.106969  0.132966   0.0  0.004219  0.000000
3    0.096508  0.136342  0.562775   0.0  0.088608  0.041667
4    0.036339  0.037001  0.008581   0.0  0.004219  0.000000
..        ...       ...       ...   ...       ...       ...
425  0.000000  0.014240  0.053098   0.0  0.067511  0.041667
426  0.177452  0.226870  0.057530   0.0  0.008439  0.000000
427  0.338447  0.228798  0.060485   0.0  0.139241  0.208333
428  0.474495  0.389528  0.101114   0.0  0.000000  0.000000
429  0.514037  0.499958  0.145436   0.0  0.139241  0.145833

[430 rows x 6 columns]

In [8]:
df_corr.to_csv('./다행히개인폴더/변수간_상관계수.csv', encoding='utf-8', index=False)

### 유의미한 독립변수로 1인가구, 생활인구, 교차로 선정

In [ ]:
inertia= []
for k in range(2,9):
    km =