In [106]:
import pandas as pd

In [107]:
df = pd.read_csv('./data/seoulAccidentInfoList.csv',encoding='utf-8')

In [108]:
df

,Unnamed: 0,index,사고일시,시군구,사고내용,사망자수,중상자수,경상자수,부상신고자수,가해운전자 차종,가해운전자 상해정도,피해운전자 차종,피해운전자 상해정도
0,0,8,2019년 1월 1일 19시,서울특별시 용산구 후암동,중상사고,0,1,0,0,승용,상해없음,이륜,중상
1,1,23,2019년 1월 2일 11시,서울특별시 성동구 용답동,중상사고,0,1,0,0,승용,상해없음,이륜,중상
2,2,25,2019년 1월 2일 12시,서울특별시 서대문구 북아현동,중상사고,0,1,0,0,이륜,중상,건설기계,상해없음
3,3,30,2019년 1월 2일 15시,서울특별시 서초구 서초동,중상사고,0,1,0,0,승용,상해없음,이륜,중상
4,4,35,2019년 1월 2일 18시,서울특별시 영등포구 여의도동,중상사고,0,1,0,0,승용,상해없음,이륜,중상
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7850,7850,26134,2021년 12월 31일 17시,서울특별시 성북구 길음동,중상사고,0,1,0,0,화물,상해없음,이륜,중상
7851,7851,26135,2021년 12월 31일 17시,서울특별시 구로구 구로동,중상사고,0,1,0,0,승용,상해없음,이륜,중상
7852,7852,26141,2021년 12월 31일 19시,서울특별시 은평구 역촌동,중상사고,0,1,0,0,이륜,상해없음,보행자,중상
7853,7853,26142,2021년 12월 31일 19시,서울특별시 송파구 삼전동,중상사고,0,1,0,1,승용,부상신고,이륜,중상
7854,7854,26143,2021년 12월 31일 19시,서울특별시 양천구 신정동,중상사고,0,1,0,0,이륜,중상,승용,상해없음

In [109]:
address_list = df['시군구'].str.split()

In [110]:
address_list.head()

0      [서울특별시, 용산구, 후암동]
1      [서울특별시, 성동구, 용답동]
2    [서울특별시, 서대문구, 북아현동]
3      [서울특별시, 서초구, 서초동]
4    [서울특별시, 영등포구, 여의도동]
Name: 시군구, dtype: object

In [111]:
df['자치구'] = address_list.str.get(1)
df['행정동'] = address_list.str.get(2)

In [112]:
df.head()

,Unnamed: 0,index,사고일시,시군구,사고내용,사망자수,중상자수,경상자수,부상신고자수,가해운전자 차종,가해운전자 상해정도,피해운전자 차종,피해운전자 상해정도,자치구,행정동
0,0,8,2019년 1월 1일 19시,서울특별시 용산구 후암동,중상사고,0,1,0,0,승용,상해없음,이륜,중상,용산구,후암동
1,1,23,2019년 1월 2일 11시,서울특별시 성동구 용답동,중상사고,0,1,0,0,승용,상해없음,이륜,중상,성동구,용답동
2,2,25,2019년 1월 2일 12시,서울특별시 서대문구 북아현동,중상사고,0,1,0,0,이륜,중상,건설기계,상해없음,서대문구,북아현동
3,3,30,2019년 1월 2일 15시,서울특별시 서초구 서초동,중상사고,0,1,0,0,승용,상해없음,이륜,중상,서초구,서초동
4,4,35,2019년 1월 2일 18시,서울특별시 영등포구 여의도동,중상사고,0,1,0,0,승용,상해없음,이륜,중상,영등포구,여의도동

In [116]:
df = df[['자치구','행정동','사망자수','중상자수','경상자수']]

In [117]:
df.groupby(['자치구','행정동']).sum()

         사망자수  중상자수  경상자수
자치구 행정동
강남구 개포동     0    39    12
    논현동     0   139    27
    대치동     3    94     7
    도곡동     1    40     9
    삼성동     0    64    16
...       ...   ...   ...
중랑구 면목동     3   154    26
    묵동      0    50     8
    상봉동     0    71    12
    신내동     0    42    11
    중화동     0    60     5

[405 rows x 3 columns]

In [118]:
df.to_csv('서울시_행정동별_교통사고통계.csv',encoding='utf-8')

In [119]:
df

       자치구   행정동  사망자수  중상자수  경상자수
0      용산구   후암동     0     1     0
1      성동구   용답동     0     1     0
2     서대문구  북아현동     0     1     0
3      서초구   서초동     0     1     0
4     영등포구  여의도동     0     1     0
...    ...   ...   ...   ...   ...
7850   성북구   길음동     0     1     0
7851   구로구   구로동     0     1     0
7852   은평구   역촌동     0     1     0
7853   송파구   삼전동     0     1     0
7854   양천구   신정동     0     1     0

[7855 rows x 5 columns]