In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
df = pd.read_excel('./data/사고통계원본.xlsx')
df

,시군구,사망자수,중상자수,경상자수,부상신고자수,도로형태,가해운전자 차종,피해운전자 차종
0,서울특별시 서초구 방배동,0,1,0,0,단일로 - 기타,기타불명,보행자
1,서울특별시 노원구 월계동,0,1,0,0,단일로 - 기타,화물,자전거
2,서울특별시 강남구 압구정동,0,1,1,0,기타 - 기타,승용,승용
3,서울특별시 중랑구 묵동,0,1,0,0,단일로 - 기타,승합,NaN
4,서울특별시 강동구 천호동,0,1,0,0,단일로 - 기타,승합,NaN
...,...,...,...,...,...,...,...,...
26143,서울특별시 양천구 신정동,0,1,0,0,교차로 - 교차로안,이륜,승용
26144,서울특별시 중구 충무로4가,0,1,0,0,교차로 - 교차로횡단보도내,승용,보행자
26145,서울특별시 마포구 서교동,0,1,0,0,단일로 - 기타,화물,보행자
26146,서울특별시 강남구 세곡동,0,1,0,0,교차로 - 교차로안,승용,보행자
26147,서울특별시 서초구 반포동,0,1,1,0,단일로 - 기타,승용,승용

In [3]:
df = df[(df['가해운전자 차종']=='이륜') |  (df['피해운전자 차종']=='이륜')]
df

,시군구,사망자수,중상자수,경상자수,부상신고자수,도로형태,가해운전자 차종,피해운전자 차종
8,서울특별시 용산구 후암동,0,1,0,0,교차로 - 교차로부근,승용,이륜
23,서울특별시 성동구 용답동,0,1,0,0,교차로 - 교차로부근,승용,이륜
25,서울특별시 서대문구 북아현동,0,1,0,0,단일로 - 기타,이륜,건설기계
30,서울특별시 서초구 서초동,0,1,0,0,교차로 - 교차로안,승용,이륜
35,서울특별시 영등포구 여의도동,0,1,0,0,교차로 - 교차로안,승용,이륜
...,...,...,...,...,...,...,...,...
26134,서울특별시 성북구 길음동,0,1,0,0,교차로 - 교차로안,화물,이륜
26135,서울특별시 구로구 구로동,0,1,0,0,교차로 - 교차로안,승용,이륜
26141,서울특별시 은평구 역촌동,0,1,0,0,단일로 - 기타,이륜,보행자
26142,서울특별시 송파구 삼전동,0,1,0,1,단일로 - 기타,승용,이륜
26143,서울특별시 양천구 신정동,0,1,0,0,교차로 - 교차로안,이륜,승용

In [4]:
df['교차로'] = 0
df['단일'] = 0
df

C:\Users\admin\AppData\Local\Temp\ipykernel_14408\1211375906.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['교차로'] = 0
C:\Users\admin\AppData\Local\Temp\ipykernel_14408\1211375906.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['단일'] = 0

,시군구,사망자수,중상자수,경상자수,부상신고자수,도로형태,가해운전자 차종,피해운전자 차종,교차로,단일
8,서울특별시 용산구 후암동,0,1,0,0,교차로 - 교차로부근,승용,이륜,0,0
23,서울특별시 성동구 용답동,0,1,0,0,교차로 - 교차로부근,승용,이륜,0,0
25,서울특별시 서대문구 북아현동,0,1,0,0,단일로 - 기타,이륜,건설기계,0,0
30,서울특별시 서초구 서초동,0,1,0,0,교차로 - 교차로안,승용,이륜,0,0
35,서울특별시 영등포구 여의도동,0,1,0,0,교차로 - 교차로안,승용,이륜,0,0
...,...,...,...,...,...,...,...,...,...,...
26134,서울특별시 성북구 길음동,0,1,0,0,교차로 - 교차로안,화물,이륜,0,0
26135,서울특별시 구로구 구로동,0,1,0,0,교차로 - 교차로안,승용,이륜,0,0
26141,서울특별시 은평구 역촌동,0,1,0,0,단일로 - 기타,이륜,보행자,0,0
26142,서울특별시 송파구 삼전동,0,1,0,1,단일로 - 기타,승용,이륜,0,0
26143,서울특별시 양천구 신정동,0,1,0,0,교차로 - 교차로안,이륜,승용,0,0

In [5]:
df

,시군구,사망자수,중상자수,경상자수,부상신고자수,도로형태,가해운전자 차종,피해운전자 차종,교차로,단일
8,서울특별시 용산구 후암동,0,1,0,0,교차로 - 교차로부근,승용,이륜,0,0
23,서울특별시 성동구 용답동,0,1,0,0,교차로 - 교차로부근,승용,이륜,0,0
25,서울특별시 서대문구 북아현동,0,1,0,0,단일로 - 기타,이륜,건설기계,0,0
30,서울특별시 서초구 서초동,0,1,0,0,교차로 - 교차로안,승용,이륜,0,0
35,서울특별시 영등포구 여의도동,0,1,0,0,교차로 - 교차로안,승용,이륜,0,0
...,...,...,...,...,...,...,...,...,...,...
26134,서울특별시 성북구 길음동,0,1,0,0,교차로 - 교차로안,화물,이륜,0,0
26135,서울특별시 구로구 구로동,0,1,0,0,교차로 - 교차로안,승용,이륜,0,0
26141,서울특별시 은평구 역촌동,0,1,0,0,단일로 - 기타,이륜,보행자,0,0
26142,서울특별시 송파구 삼전동,0,1,0,1,단일로 - 기타,승용,이륜,0,0
26143,서울특별시 양천구 신정동,0,1,0,0,교차로 - 교차로안,이륜,승용,0,0

In [6]:
df['도로형태'] = df['도로형태'].str.split().str.get(0)
df

C:\Users\admin\AppData\Local\Temp\ipykernel_14408\3148891133.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['도로형태'] = df['도로형태'].str.split().str.get(0)

,시군구,사망자수,중상자수,경상자수,부상신고자수,도로형태,가해운전자 차종,피해운전자 차종,교차로,단일
8,서울특별시 용산구 후암동,0,1,0,0,교차로,승용,이륜,0,0
23,서울특별시 성동구 용답동,0,1,0,0,교차로,승용,이륜,0,0
25,서울특별시 서대문구 북아현동,0,1,0,0,단일로,이륜,건설기계,0,0
30,서울특별시 서초구 서초동,0,1,0,0,교차로,승용,이륜,0,0
35,서울특별시 영등포구 여의도동,0,1,0,0,교차로,승용,이륜,0,0
...,...,...,...,...,...,...,...,...,...,...
26134,서울특별시 성북구 길음동,0,1,0,0,교차로,화물,이륜,0,0
26135,서울특별시 구로구 구로동,0,1,0,0,교차로,승용,이륜,0,0
26141,서울특별시 은평구 역촌동,0,1,0,0,단일로,이륜,보행자,0,0
26142,서울특별시 송파구 삼전동,0,1,0,1,단일로,승용,이륜,0,0
26143,서울특별시 양천구 신정동,0,1,0,0,교차로,이륜,승용,0,0

In [7]:
df = df.reset_index(drop=True)
df

,시군구,사망자수,중상자수,경상자수,부상신고자수,도로형태,가해운전자 차종,피해운전자 차종,교차로,단일
0,서울특별시 용산구 후암동,0,1,0,0,교차로,승용,이륜,0,0
1,서울특별시 성동구 용답동,0,1,0,0,교차로,승용,이륜,0,0
2,서울특별시 서대문구 북아현동,0,1,0,0,단일로,이륜,건설기계,0,0
3,서울특별시 서초구 서초동,0,1,0,0,교차로,승용,이륜,0,0
4,서울특별시 영등포구 여의도동,0,1,0,0,교차로,승용,이륜,0,0
...,...,...,...,...,...,...,...,...,...,...
7850,서울특별시 성북구 길음동,0,1,0,0,교차로,화물,이륜,0,0
7851,서울특별시 구로구 구로동,0,1,0,0,교차로,승용,이륜,0,0
7852,서울특별시 은평구 역촌동,0,1,0,0,단일로,이륜,보행자,0,0
7853,서울특별시 송파구 삼전동,0,1,0,1,단일로,승용,이륜,0,0
7854,서울특별시 양천구 신정동,0,1,0,0,교차로,이륜,승용,0,0

In [8]:
df['행정동'] = df['시군구'].str.split().str.get(-1)
df['구'] = df['시군구'].str.split().str.get(1)
# df.drop(columns=['시군구'])
df

,시군구,사망자수,중상자수,경상자수,부상신고자수,도로형태,가해운전자 차종,피해운전자 차종,교차로,단일,행정동,구
0,서울특별시 용산구 후암동,0,1,0,0,교차로,승용,이륜,0,0,후암동,용산구
1,서울특별시 성동구 용답동,0,1,0,0,교차로,승용,이륜,0,0,용답동,성동구
2,서울특별시 서대문구 북아현동,0,1,0,0,단일로,이륜,건설기계,0,0,북아현동,서대문구
3,서울특별시 서초구 서초동,0,1,0,0,교차로,승용,이륜,0,0,서초동,서초구
4,서울특별시 영등포구 여의도동,0,1,0,0,교차로,승용,이륜,0,0,여의도동,영등포구
...,...,...,...,...,...,...,...,...,...,...,...,...
7850,서울특별시 성북구 길음동,0,1,0,0,교차로,화물,이륜,0,0,길음동,성북구
7851,서울특별시 구로구 구로동,0,1,0,0,교차로,승용,이륜,0,0,구로동,구로구
7852,서울특별시 은평구 역촌동,0,1,0,0,단일로,이륜,보행자,0,0,역촌동,은평구
7853,서울특별시 송파구 삼전동,0,1,0,1,단일로,승용,이륜,0,0,삼전동,송파구
7854,서울특별시 양천구 신정동,0,1,0,0,교차로,이륜,승용,0,0,신정동,양천구

In [9]:
# for i in range(len(df)):
#     if df['도로형태'][i] == '교차로':
#         df['교차로'][i] = 1
#     elif df['도로형태'][i] == '단일로':
#         df['단일'][i] = 1
#     else:
#         continue

# df

hi